version: '3.4'

services:

  db:
    
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=metrobus
    expose: 
      - 5432
    networks:
      - fastapi-network

  Unidades_Metrobus:
    image: "tiangolo/uvicorn-gunicorn-fastapi:python3.7"
    depends_on:
      - db
    build: ./Unidades_Metrobus
    
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"  
    volumes:
      - ./Unidades_Metrobus:/Unidades_Metrobus
      
    container_name: micro-service-fastapi
    networks:
      - fastapi-network

networks: 
  fastapi-network:
    driver: bridge


volumes:
  postgres_data: